### ISSUE TITLE
More parameters in getTaskDictionary

### ISSUE THREAD

**Issue by TuSKan** [jakob-r/mlrHyperopt#15]
Its possible to include a new parameter _t_ on _getTaskDictionary_  as below?
```r
getTaskDictionary = function(task) {
  assertClass(task, classes = "Task")
  dict = list(
    task = task,
    p = getTaskNFeats(task),
    n.task = getTaskSize(task),
    type = getTaskType(task),
    n = getTaskSize(task)
  )
  if (dict$type == "classif") {
    dict$k = length(getTaskClassLevels(task))
    dict$t = summary(getTaskTargets(task))
  }
  return(dict)
}
```
it will be useful for config the **nu** parameter of **svm** as below:
```r
makeNumericParam(id = "nu", default = 0.2, lower = 0.01, upper = expression(2.0 * min(t) / n - 0.01))
```
ref: [https://www.csie.ntu.edu.tw/~cjlin/papers/nusvmtutorial.pdf](https://www.csie.ntu.edu.tw/~cjlin/papers/nusvmtutorial.pdf) page 17

**Comment by jakob-r** [comment]
Good idea. Done in a8f03d511b2e0da15fde4b033b03298a88726547

**Comment by TuSKan** [comment]
What do you think to add more parameters in getTaskDictionary ?

```r
getTaskDictionary = function(task) {
  assertClass(task, classes = "Task")
  dict = list(
    task = task,
    p = getTaskNFeats(task),
    n.task = getTaskSize(task),
    type = getTaskType(task),
    n = getTaskSize(task),
    maxy = max(getTaskTargets(task)),
    miny = min(getTaskTargets(task))
  )
  if (dict$type == "classif") {
    dict$k = length(getTaskClassLevels(task))
    dict$t = summary(getTaskTargets(task))
  }
  return(dict)
}
```
it will be useful for config the **epsilon** parameter of **svm** as below:
```r 
makeNumericParam(id = "epsilon", default = 0.001, lower = 0, upper = expression((maxy - miny) / 2))
```

ref: [http://ntur.lib.ntu.edu.tw/bitstream/246246/155227/1/14.pdf](http://ntur.lib.ntu.edu.tw/bitstream/246246/155227/1/14.pdf)

**Comment by jakob-r** [comment]
That gets very particular. You can always access the task itself as it's part of the dictionary. I have not looked into the link but I guess you could do `upper = expression((max(getTaskTargets(task)) - min(getTaskTargets(task)))/2)`.
