### ISSUE TITLE
Link on homepage is broken

### ISSUE THREAD

**Issue by juliabrosig** [jakob-r/mlrHyperopt#21]
Reproducibility
This package is still under construction and the inner workings might change without a version number update. Thus I do not recommend the usage for reproducible research until it is on CRAN. For reproducible research you might want to stick to the more lengthly but more precise **mlr tuning workflow.** You can still use the Parameter Sets recommended in mlrHyperopt. Just make sure to write them in your source code.

The **marked link** is not working anymore

**Comment by jakob-r** [comment]
Is now fixed. Thanks for reporting.
