### ISSUE TITLE
hyperparameter range db - community fed range predictions

### ISSUE THREAD

**Issue by KnutJaegersberg** [jakob-r/mlrHyperopt#25]
really like this feature. shouldnt it be possible to next to create a community driven db of ranges to also apply ml on general shape of the datasets (summary stats / topological data analysis) to predict effective hyperparameter ranges fed by community results?

**Comment by jakob-r** [comment]
> apply ml on general shape of the data sets

To my knowledge, such meta-learning seldom really worked out if the data sets are too different. If you know something I gladly will look into it. 
However, there is the OpenML Database which does not only store data sets but also the performance of many hyperparameter configurations. These were taken to calculate sensible tuning ranges https://arxiv.org/abs/1802.09596 or to find interesting set of defaults http://metalearning.ml/2018/papers/metalearn2018_paper70.pdf
To incorporate this knowledge in some easily usable software would need some funding, though.

After all it would be part of a separate project, therefore I will close this issue.
