### ISSUE TITLE
Deprecations

### ISSUE THREAD

**Issue by jdcohnsfnm** [jakob-r/mlrHyperopt#26]
I use mlrHyperopt quite frequently.  Recently I have started getting deprecation warnings from R when using mlrHyperopt.  The first occurs on all my computers and is related to the mlr package being deprecated  with all development being moved to mlr3.  Are there plans to update the code to mlr3?  The second type of deprecation message occurs when I am running hyperopt with a RegrTask using Learner for "regr.xgboost".    This message repeatedly tells me that reg:linear has been replaced with reg:squarederror.  I presume the task and learner have reg:linear hard-coded for Learner "regr.xgboost".  This only occurs on my newest computer running R 4.0 rather than R 3.5 or 3.6 on my other computers.  Is there a Learner string I can use other than regr.xgboost that will use reg:squarederror instead of reg:linear? Or do I need to create my own Learner object.   I hate to suppress all warnings in case there is some other warning I don't know about.  Thanks for all your work on mlrHyperopt!

**Comment by jakob-r** [comment]
Hi, thanks for reaching out.
Currently, we are working on mlr3, mlr3tuning, mlr3mbo and [mlr3automl](https://github.com/a-hanf/mlr3automl). Especially the later will make tuning easy as it also tunes over the choice of the learner. 

As the message says mlr is currently not further developed. So this message won't go away. Nonetheless, the `regr.xgboost` issue was solved in mlr https://github.com/mlr-org/mlr/commit/5882ca92b19e97b3a0408d5fdb2e6aeb4509a9ca. You can either install from GitHub or wait until the next cran release.

**Comment by jakob-r** [comment]
mlr 2.18.0 was just released to CRAN. So updates within the next weeks should remove the xgboost warning.
